### ISSUE TITLE
Question about Kong workshop

### ISSUE THREAD

**Issue by jkvargas** [aws-samples/aws-modernization-with-kong#5]
I was checking this documentation https://kong.awsworkshop.io/plugin-resources/oidc.html ,
I believe that I need to have a AWS::ECS::TaskDefinition with image being kong-2.3.3 
and environment as described at the webpage,

```
ContainerDefinitions:
        - Name: ...
          Image: ...
          ...
          Environment:
            ...
            - Name: COGNITO_CLIENT_ID
              Value: !Ref CognitoClientId
            - Name: COGNITO_POOL_ID
              Value: !Ref CognitoPoolId
            - Name: ISSUER
              Value: !Join
                - '-'
                - - 'https://cognito-idp.'
                  - !Ref Region
                  - '.amazonaws.com/'
                  - !Ref CognitoPoolId
                  - '/.well-known/openid-configuration'
            - Name: CLIENT_SECRET
              Value: !Ref CognitoSecret
```

So, considering that I got right to this part,
how should I pragmatically add the plugin for auth against cognito?
Do I need to change something at the image level?
Thanks in advance.
